#!/bin/sh
rm -rf $HOME/.visit/simulations/*
rm -rf /dev/shm/damaris-*
NP=$1
PROG=$2
shift
shift

LD_LIBRARY_PATH=$HOME/local/visit/2.8.1/linux-x86_64/lib:$HOME/local/visit/2.8.1/linux-x86_64/lib/osmesa:$LD_LIBRARY_PATH mpirun -np $NP ./$PROG $@

#LD_LIBRARY_PATH=. \
#mpirun -np 3 ./mandelbulb $1
